# Generated by Django 5.1.7 on 2026-05-30 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['tournament', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['tournament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(14, 0))),
                ('num_courts', models.PositiveSmallIntegerField(default=4)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=25)),
                ('num_groups', models.PositiveSmallIntegerField(default=4)),
                ('teams_per_group', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('group', 'Fase a gironi'), ('knockout', 'Eliminazione diretta'), ('done', 'Concluso')], default='setup', max_length=12)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('player1', models.CharField(max_length=80)),
                ('player2', models.CharField(max_length=80)),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='tournaments.group')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['group__name', 'seed', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('group', 'Girone'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=8)),
                ('round_label', models.CharField(blank=True, max_length=40)),
                ('bracket_pos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slot_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('games_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('games_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiebreak_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiebreak_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmata'), ('live', 'In corso'), ('done', 'Finita')], default='scheduled', max_length=10)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.court')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.group')),
                ('source_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_a', to='tournaments.match')),
                ('source_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_b', to='tournaments.match')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='tournaments.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='tournaments.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['slot_index', 'court__number', 'bracket_pos'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='court',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('tournament', 'number')},
        ),
    ]
