# Generated by Django 5.1.7 on 2026-05-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='games_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='games_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tiebreak_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tiebreak_b',
        ),
        migrations.AddField(
            model_name='match',
            name='slot_span',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('games_a', models.PositiveSmallIntegerField()),
                ('games_b', models.PositiveSmallIntegerField()),
                ('tiebreak_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiebreak_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tournaments.match')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('match', 'number')},
            },
        ),
    ]
