# Generated by Django 5.1.7 on 2026-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_match_games_a_remove_match_games_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='source_a_role',
            field=models.CharField(choices=[('winner', 'Vincente'), ('loser', 'Perdente')], default='winner', max_length=6),
        ),
        migrations.AddField(
            model_name='match',
            name='source_b_role',
            field=models.CharField(choices=[('winner', 'Vincente'), ('loser', 'Perdente')], default='winner', max_length=6),
        ),
    ]
