# Generated by Django 5.1.7 on 2026-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match_source_a_role_match_source_b_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='walkover',
            field=models.BooleanField(default=False),
        ),
    ]
