# Generated by Django 5.1.7 on 2026-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_scorelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='num_groups',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
