# Generated by Django 5.1.7 on 2026-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_num_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spareggio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
